# Generated by Django 4.2 on 2023-11-12 00:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('archives', '0006_alter_genus_image_alter_species_image_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='genus',
            name='image',
            field=models.ImageField(default='default.jpg', upload_to='media/images/'),
        ),
        migrations.AlterField(
            model_name='species',
            name='image',
            field=models.ImageField(default='default.jpg', upload_to='blu_thumb/media/images/'),
        ),
        migrations.AlterField(
            model_name='variety',
            name='image',
            field=models.ImageField(default='default.jpg', upload_to='blu_thumb/media/images/'),
        ),
    ]
