# Generated by Django 4.2 on 2023-11-12 06:04

from django.db import migrations
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('archives', '0007_alter_genus_image_alter_species_image_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='genus',
            options={},
        ),
        migrations.AddField(
            model_name='genus',
            name='host_trees',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('Deciduous', 'Deciduous'), ('Coniferous', 'Coniferous')], default=[], max_length=255, verbose_name='Host Trees'),
        ),
        migrations.AddField(
            model_name='genus',
            name='sub_pref',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('Compost', 'Compost'), ('Grain', 'Grain'), ('Manure', 'Manure'), ('Straw', 'Straw'), ('Wood', 'Wood')], default=[], max_length=255, verbose_name='Substrate Preference(s)'),
        ),
        migrations.AlterField(
            model_name='genus',
            name='fav_eco',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('Alpine', 'Alpine'), ('Coastal', 'Coastal'), ('Desert', 'Desert'), ('Forest', 'Forest'), ('Grassland', 'Gassland'), ('Urban', 'Urban'), ('Wetland', 'Wetland')], default=[], max_length=255, verbose_name='Favored Ecosystem(s)'),
        ),
        migrations.AlterField(
            model_name='genus',
            name='geo_loc',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('Africa', 'Africa'), ('Antarctica', 'Antarctica'), ('Asia', 'Asia'), ('Europe', 'Europe'), ('North America', 'North America'), ('Oceania', 'Oceania'), ('South America', 'South America')], default=[], max_length=255, verbose_name='Geographic Location(s)'),
        ),
    ]
