# Generated by Django 4.2 on 2023-11-12 14:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('archives', '0008_alter_genus_options_genus_host_trees_genus_sub_pref_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='genus',
            options={'verbose_name_plural': 'Genera'},
        ),
    ]
