# Generated by Django 4.2 on 2023-05-06 15:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Genus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('genus_name', models.CharField(max_length=150, verbose_name='Genus')),
            ],
        ),
        migrations.CreateModel(
            name='Species',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('species_name', models.CharField(max_length=150, verbose_name='Species')),
                ('genus', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='archive.genus')),
            ],
        ),
        migrations.CreateModel(
            name='Variety',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('variety_name', models.CharField(max_length=150, verbose_name='Variety')),
                ('species', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='archive.species')),
            ],
        ),
        migrations.CreateModel(
            name='Substrate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subsrtate_name', models.CharField(max_length=150, verbose_name='Substrate')),
                ('variety', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='archive.variety')),
            ],
        ),
    ]
