# Generated by Django 4.2 on 2023-05-14 12:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('archive', '0002_alter_genus_options_alter_species_options_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Substrate',
        ),
    ]
