# Generated by Django 4.2 on 2023-06-04 15:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('archive', '0003_delete_substrate'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='genus',
            options={'verbose_name_plural': 'Genera'},
        ),
        migrations.AddField(
            model_name='genus',
            name='fav_eco',
            field=models.CharField(default='', max_length=255, verbose_name='Favored Ecosystem(s)'),
        ),
        migrations.AddField(
            model_name='genus',
            name='geo_loc',
            field=models.CharField(default='', max_length=255, verbose_name='Geographic Location(s)'),
        ),
        migrations.AddField(
            model_name='genus',
            name='image',
            field=models.ImageField(default='default.jpg', upload_to='images/'),
        ),
        migrations.AddField(
            model_name='species',
            name='fav_eco',
            field=models.CharField(default='', max_length=255, verbose_name='Favored Ecosystem(s)'),
        ),
        migrations.AddField(
            model_name='species',
            name='geo_loc',
            field=models.CharField(default='', max_length=255, verbose_name='Geographic Location(s)'),
        ),
        migrations.AddField(
            model_name='species',
            name='image',
            field=models.ImageField(default='default.jpg', upload_to='images/'),
        ),
        migrations.AddField(
            model_name='species',
            name='indoor_cultivation',
            field=models.BooleanField(default=True, verbose_name='Indoor Cultivation'),
        ),
        migrations.AddField(
            model_name='species',
            name='medicinal',
            field=models.BooleanField(default=False, verbose_name='Medicinal'),
        ),
        migrations.AddField(
            model_name='variety',
            name='image',
            field=models.ImageField(default='default.jpg', upload_to='images/'),
        ),
    ]
