# Generated by Django 4.2 on 2023-06-10 13:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('archive', '0005_alter_species_indoor_cultivation_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='genus',
            name='image',
            field=models.ImageField(default='default.jpg', upload_to='media/'),
        ),
        migrations.AlterField(
            model_name='species',
            name='image',
            field=models.ImageField(default='default.jpg', upload_to='media/'),
        ),
        migrations.AlterField(
            model_name='variety',
            name='image',
            field=models.ImageField(default='default.jpg', upload_to='media/'),
        ),
    ]
